name: $(Build.BuildID)

pool:
  vmImage: "ubuntu-20.04"

steps:
  - task: Docker@2
    inputs:
      containerRegistry: 'official-docker-modmoto'
      repository: 'modmoto/deploynator'
      command: 'buildAndPush'
      Dockerfile: '**/Dockerfile'
      buildContext: '.'
      tags: |
        $(Build.BuildID),
        latest

  - task: CopyFiles@2
    displayName: publish docker-compose files
    inputs:
      contents: '**/*docker-compose.yml'
      targetFolder: $(Build.ArtifactStagingDirectory)

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: $(Build.ArtifactStagingDirectory)